/*
 * Copyright 2020 Matt Jamesson <scifidryer@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package modbusmechanic;

/**
 *
 * @author Matt Jamesson <scifidryer@gmail.com>
 */
public class SlaveWatchWindow extends javax.swing.JFrame {

    /**
     * Creates new form SlaveWatchWindow
     */
    public SlaveWatchWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        autoScrollCheckbox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        clearScrollbackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        msgTextArea.setEditable(false);
        msgTextArea.setColumns(60);
        msgTextArea.setRows(10);
        jScrollPane1.setViewportView(msgTextArea);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1);

        autoScrollCheckbox.setSelected(true);
        autoScrollCheckbox.setText("Auto scroll");
        jPanel3.add(autoScrollCheckbox);

        getContentPane().add(jPanel3);

        clearScrollbackButton.setText("Clear scrollback");
        clearScrollbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearScrollbackButtonActionPerformed(evt);
            }
        });
        jPanel2.add(clearScrollbackButton);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearScrollbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearScrollbackButtonActionPerformed
        msgTextArea.setText("");
    }//GEN-LAST:event_clearScrollbackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SlaveWatchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SlaveWatchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SlaveWatchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SlaveWatchWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SlaveWatchWindow watchWindow = new SlaveWatchWindow();
                watchWindow.setVisible(true);
                ModbusMechanic.watchWindow = watchWindow;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox autoScrollCheckbox;
    private javax.swing.JButton clearScrollbackButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea msgTextArea;
    // End of variables declaration//GEN-END:variables
}
